# 建库与数据库切换
CREATE DATABASE bc_prod;
use bc_prod;

# 建表

# 用户表
DROP TABLE IF EXISTS BC_USER;
CREATE TABLE `BC_USER` (
        ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
        ACCOUNT VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户账号',
        `PASSWORD` VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户密码',
        USER_NAME VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户昵称',
        `POINT` INT NOT NULL DEFAULT 0 COMMENT '积分',
        INVITER BIGINT DEFAULT NULL COMMENT '邀请人',
        INVITATION_CODE VARCHAR(5) NOT NULL DEFAULT '' COMMENT '邀请码',
        BAN_TIME DATETIME COMMENT '封禁日期',
        GMT_CREATE DATETIME COMMENT '创建时间',
        GMT_MODIFIED DATETIME COMMENT '修改时间',
        DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户信息表';

# Fetal Movement
DROP TABLE IF EXISTS BC_FETAL_MOVEMENT;
CREATE TABLE `BC_FETAL_MOVEMENT` (
        ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
        USER_ID BIGINT NOT NULL COMMENT '用户ID',
        VALID_COUNT INT NOT NULL DEFAULT 0 COMMENT '有效次数',
        TOTAL_COUNT INT NOT NULL DEFAULT 0 COMMENT '总次数',
        START_TIME DATETIME COMMENT '开始时间',
        END_TIME DATETIME COMMENT '结束时间',
        GMT_CREATE DATETIME COMMENT '创建时间',
        GMT_MODIFIED DATETIME COMMENT '修改时间',
        DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Fetal Movement表';

# Fetal Movement Count
DROP TABLE IF EXISTS BC_FETAL_MOVEMENT_COUNT;
CREATE TABLE `BC_FETAL_MOVEMENT_COUNT` (
        ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
        FM_ID BIGINT NOT NULL COMMENT 'FM ID',
        USER_ID BIGINT NOT NULL COMMENT '用户ID',
        CLICK_TIME DATETIME COMMENT '点击时间',
        GMT_CREATE DATETIME COMMENT '创建时间',
        GMT_MODIFIED DATETIME COMMENT '修改时间',
        DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Fetal Movement Count表';

